### PR TITLE
Make mutex cross-platform

### PR DESCRIPTION
**Pull request by tclancy**
Changed from the hard-coded `'/tmp/'` to [`tempfile.gettempdir()`](https://docs.python.org/2/library/tempfile.html#tempfile.gettempdir) to allow the mutex logic to work on Windows.

### CODE REVIEW

**Comment by specialunderwear** [comment]
Nice!

I will need to check the whitespace changes tomorrow, because windows. Also could you be bothered to squash your commits into 1 working clean commit?

**Comment by tclancy** [comment]
Sure, what's the cleanest/ easiest way to do that?

**Comment by specialunderwear** [comment]
Git rebase -i HEAD^^
Git push --force

**Comment by tclancy** [comment]
Done.

**Pull request merged**
